"""'001'

Revision ID: 87598eaf3c66
Revises: 
Create Date: 2017-07-05 10:48:28.452610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87598eaf3c66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reply', 'userinfo', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'receiver_id')
    # ### end Alembic commands ###
